### ISSUE TITLE
Options arguments are being required

### ISSUE THREAD

**Issue by John4266** [OutwalkStudios/discord-backup#4]
Hello there and thank you for keeping this package maintained.

When creating a backup, Typescript says all options are required to be set.
![image](https://user-images.githubusercontent.com/70203256/187856053-33325b9c-f183-4c70-9509-0de8cc91b061.png)
However, this shouldn't be the case because the code fallbacks to default options.
https://github.com/OutwalkStudios/discord-backup/blob/13c1d17d1474a99d64352460eeaedf391cfdccd7/src/index.js#L53-L62

This happens because the typings for `Options`'s fields are not optional
https://github.com/OutwalkStudios/discord-backup/blob/13c1d17d1474a99d64352460eeaedf391cfdccd7/types/index.d.ts#L3-L11

where in the original package all the options are optional
https://github.com/Androz2091/discord-backup/blob/5cb05fcfa1ede46731652af2a63eaccae929ce08/src/types/CreateOptions.ts#L1-L9

**Comment by jleeson** [comment]
Good catch, thank you for pointing this out @John4266, I will get this fixed and pushed in a release tomorrow morning.

**Comment by jleeson** [comment]
This has been fixed in v0.4.5, let me know if there is anything else that can be improved @John4266.

**Comment by John4266** [comment]
> This has been fixed in v0.4.5, let me know if there is anything else that can be improved @John4266.

Hi.
Unfortunately, this doesn't really fix it since it only makes the argument itself optional but not its fields.
![image](https://user-images.githubusercontent.com/70203256/188015212-0d92ea31-e7bb-46fa-98dd-35234cb2f32a.png)
![image](https://user-images.githubusercontent.com/70203256/188015149-3ed97061-3b45-4112-85e9-417ce68ef100.png)

You need to modify these lines:
https://github.com/OutwalkStudios/discord-backup/blob/13c1d17d1474a99d64352460eeaedf391cfdccd7/types/index.d.ts#L3-L11
to look like this:

```ts
 export declare interface Options { 
     backupId?: string, 
     maxMessagesPerChannel?: number, 
     jsonSave?: boolean, 
     jsonBeautify?: boolean, 
     doNotBackup?: string[], 
     saveImages?: string, 
     speed?: number 
 }
```

**Comment by jleeson** [comment]
Your right, my bad. Its been a while since i worked with TypeScript. This should be resolved in v0.4.6

**Comment by John4266** [comment]
hi. i came across another issues:
1. `saveImages` type doesn't match the default value's type.
index.d.ts:
https://github.com/OutwalkStudios/discord-backup/blob/8c476999e8bcfa72e1d69200bd48fca6e434ad72/types/index.d.ts#L9
index.js:
https://github.com/OutwalkStudios/discord-backup/blob/8c476999e8bcfa72e1d69200bd48fca6e434ad72/src/index.js#L60

2. `speed` doesn't have a default value:
index.d.ts:
https://github.com/OutwalkStudios/discord-backup/blob/8c476999e8bcfa72e1d69200bd48fca6e434ad72/types/index.d.ts#L10
index.js:
https://github.com/OutwalkStudios/discord-backup/blob/8c476999e8bcfa72e1d69200bd48fca6e434ad72/src/index.js#L60-L62

**Comment by jleeson** [comment]
@John4266 for problem 1 its tricky cause for the time being I want to keep compatibility with the original discord-backup package. So it needs to support setting saveImages to false in order to completely disable saving images and setting it to base64 to make it save images as base64. The original package has a bug with the default value of the `saveImages` property which is why in this package it uses a boolean. For the types, i updated it to accept either a boolean or a string.

as for problem 2, i have updated the speed option to have a default value. The speed option is only used in the load function where rate limiting can occur, in this case it already had a default value, but i added it to the create function as well in case it's used in the future.

Let me know if there are any other problems you come across.

**Comment by John4266** [comment]
Oh, alright.
And do you think you could also provide types for the `create` method's output?
so auto completion could be used to get its properties.
Because at the moment it's just a generic object:
![](https://i.imgur.com/4w4HiFb.png)
![](https://i.imgur.com/ZNd378S.png)

**Comment by jleeson** [comment]
When I have some time, I will update the types to include the return types and make it more explicit which options create/load accept. What use case do you have for accessing the returned data?

**Comment by John4266** [comment]
I am using MongoDB (mongoose) with Typescript so having types would be very helpful for adding a backup model.

**Comment by jleeson** [comment]
Ok that makes sense, I originally had to build this package for a client project which has ended, so next time I get some time freed up, I will make sure i update the types to be as complete as possible.

**Comment by jleeson** [comment]
@John4266, I just pushed v0.4.8 which contains full typescript types based on the original package. Hope that helps. Let me know if there are any further issues.

**Comment by John4266** [comment]
Sounds great, thank you!
I'll let you know if I find more issues.
